projects:

  - id: project1
    name: project1
    repo: https://github.com/gayathri02-02/project1.git
    branch: main
    enabled: true

  - id: project2
    name: project2
    repo: https://github.com/gayathri02-02/project2.git
    branch: main
    enabled: true

  - id: project3
    name: project3
    repo: https://github.com/gayathri02-02/project3.git
    branch: main
    enabled: true
